import type {
  CuriousConversation,
  CuriousConversationChoice,
  CuriousMemoryEffect,
  DialogueBeat,
} from '../conversationTypes';

const say = (...texts: string[]): DialogueBeat[] => texts.map((text) => ({ text }));
const stage = (action: string, emotion?: DialogueBeat['emotion']): DialogueBeat => ({ action, emotion });
const think: DialogueBeat = { pauseMs: 520, emotion: 'THINKING', action: 'think' };
const pause: DialogueBeat = { pauseMs: 420, action: 'pause' };

function choice(
  id: string,
  label: string,
  response: DialogueBeat[],
  memory: CuriousMemoryEffect = {},
): CuriousConversationChoice {
  return { id, label, response, memory };
}

const DAY02_CURIOUS_01: CuriousConversation = {
  id: 'DAY02_CURIOUS_01',
  day: 2,
  category: 'CURIOUS',
  title: '人間さんの一日は、何から始まるの？',
  opening: [
    ...say('人間さん。', 'ぼく、さっき考えてたの。'),
    stage('look_window'),
    ...say('朝になると、部屋が明るくなるでしょ。', 'でも、明るくなっただけじゃ。', '何も始まってない気がするの。', 'ぼくが起きて。', 'ベッドから出て。', '何かしたら、やっと一日が始まる感じ。'),
    think,
    ...say('……。', 'でも、人間さんはどうなの？', '朝起きて、最初によくすることって何？'),
  ],
  context: { category: 'ACTIVITY', humanRelations: ['FREQUENTLY_DOES'] },
  common: {
    response: [
      ...say('{word}。', '人間さんは、それを朝にするんだね。'),
      think,
      ...say('じゃあ、それって。', '毎朝、必ずするの？'),
    ],
    choices: [
      choice('DAY02_CURIOUS_01_EVERY_MORNING', '毎朝する', [
        ...say('毎朝！', 'おお。', 'じゃあ、人間さんの朝には決まりがあるんだね。'),
        stage('impressed', 'HAPPY'),
        ...say('ぼくも決めようかな。'),
        stage('count_fingers'),
        ...say('まず、起きる。', '次に、人間さんにあいさつ。', 'それから……。'),
        think,
        ...say('……二度寝。', 'いや。', 'これじゃ、朝が終わっちゃうの。'),
        stage('troubled', 'TROUBLED'),
        ...say('でも、毎朝同じことをしてたら。', '考えなくてもできるようになるのかな。', 'じゃあ、ぼくも一個くらい続けてみる。'),
        stage('smug', 'SMUG'),
        ...say('明日から、毎朝ちゃんと起きるの！'),
        pause,
        ...say('……。', '起きる時間は、まだ決めてなかった。'),
      ], { relationQualifier: '朝に毎日する', openQuestions: [{ field: 'DETAIL', questionHint: '朝のどんな順番でそのことをするのか' }] }),
      choice('DAY02_CURIOUS_01_WHEN_FEEL_LIKE', '気が向いた時にする', [
        ...say('気が向いた時？', 'じゃあ、気が向かなかったらしないの？'),
        think,
        ...say('……。', '気って、どっちに向くの？'),
        stage('look_self'),
        ...say('右？', '左？'),
        pause,
        ...say('……そういうことじゃない？'),
        stage('bashful', 'TROUBLED'),
        ...say('ぼく、知らない言葉がまた増えたの。', 'でもさ。', '気が向いたらやるってことは。', '人間さんが自分で決めてるんだよね。'),
        stage('smug', 'SMUG'),
        ...say('じゃあ、ぼくも明日の朝は。', '起きてから何をするか決めるの。'),
        pause,
        ...say('……。', 'でも、起きる気が向かなかったら？'),
        stage('look_bed'),
        ...say('……。', 'それは、ちょっと困るの。'),
      ], { relationQualifier: '朝に気が向いた時にする', openQuestions: [{ field: 'REASON', questionHint: '朝にそれをしたくなるのはどんな時か' }] }),
      choice('DAY02_CURIOUS_01_VARIES', '日によって違う', [
        ...say('日によるの？'),
        stage('tilt_head', 'THINKING'),
        ...say('同じ人間さんなのに？', '昨日は{word}をして。', '今日は、しないかもしれない。'),
        think,
        ...say('じゃあ、人間さんの朝って。', '毎日同じじゃないんだね。'),
        pause,
        ...say('……。', 'ぼく、一回教えてもらったら。', 'ずっとそうすると思ってたの。'),
        stage('troubled', 'TROUBLED'),
        ...say('これじゃ、覚えるのが大変なの。', '……でも。', '今日は何をしたか、また聞けばいいのか。'),
        stage('happy', 'HAPPY'),
        ...say('じゃあ、明日の朝も違うことをしてるかもしれないね。', 'ぼくも明日、違う起き方をしてみようかな。'),
        pause,
        ...say('……逆立ちして起きるとか。'),
        think,
        ...say('やっぱり、普通に起きるの。'),
      ], { relationQualifier: '朝にすることは日によって違う', openQuestions: [{ field: 'DETAIL', questionHint: '日によって朝に何を変えるのか' }] }),
    ],
  },
};

const DAY02_CURIOUS_02: CuriousConversation = {
  id: 'DAY02_CURIOUS_02',
  day: 2,
  category: 'CURIOUS',
  title: '元気がない時、どうするの？',
  opening: [
    ...say('ねえ、人間さん。', 'ぼく、今日ちょっと変なことがあったの。', 'さっきまで元気だったのに。', '急に、何もしたくなくなったの。'),
    think,
    ...say('どこか痛いわけじゃないよ。', 'ただ、ぼーっとしたかったの。', 'それで、少し座ってたら。', 'また歩きたくなった。'),
    stage('smug', 'SMUG'),
    ...say('元に戻ったの。'),
    pause,
    ...say('でも、人間さんはどうなの？', '元気が出ない時ってある？', 'そういう時、何をすると少し楽になるの？'),
  ],
  context: { category: 'ACTIVITY', humanRelations: ['USED_FOR'] },
  common: {
    response: [
      ...say('{word}。', '人間さんは元気がない時に、それをするんだね。'),
      think,
      ...say('じゃあ、{word}をすると。', 'すぐ元気になる？'),
    ],
    choices: [
      choice('DAY02_CURIOUS_02_IMMEDIATE', 'すぐに元気になる', [
        ...say('すぐに？'),
        stage('sparkle', 'HAPPY'),
        ...say('すごいの！', 'じゃあ、人間さんが元気なくなったら。', '{word}をすればいいんだ。'),
        stage('smug', 'SMUG'),
        ...say('覚えたの。'),
        pause,
        ...say('……でも。', '何回もやったら、もっと元気になる？'),
        stage('count_fingers'),
        ...say('一回で元気。', '二回で、もっと元気。', '十回やったら……。'),
        stage('arms_wide', 'HAPPY'),
        ...say('ものすごく元気！'),
        pause,
        ...say('……。', 'そんなに元気になったら、寝られなくなりそう。'),
        think,
        ...say('じゃあ、元気になったらやめればいいのか。', '……人間さん。', '元気になったかどうかって、自分で分かる？'),
        stage('small', 'TROUBLED'),
        ...say('ぼく、元気なつもりでも眠い時あるの。'),
      ], { relationQualifier: '元気がない時に使うとすぐ元気になる', openQuestions: [{ field: 'DETAIL', questionHint: 'どんな時に特に役に立つのか' }] }),
      choice('DAY02_CURIOUS_02_GRADUAL', '少しずつ楽になる', [
        ...say('少しずつ。', '……ふむ。', 'じゃあ、すぐには変わらないんだ。'),
        think,
        ...say('ぼく、元気がない時は。', '何かしたら、すぐ元気になると思ってたの。', 'でも、そうじゃないこともあるのか。'),
        pause,
        ...say('じゃあ、{word}をしてる途中で。', 'まだ元気にならなかったら。', 'それでも続ける？', '……。', 'ぼくだったら、すぐ違うことを始めそうなの。'),
        stage('troubled', 'TROUBLED'),
        ...say('全然変わらないって思って。', 'でも、あとから楽になることもあるんだね。'),
        stage('understood', 'THINKING'),
        ...say('じゃあ、ぼくも。', 'すぐ変わらなくても、少し待ってみる。'),
        pause,
        ...say('……。', 'でも、退屈になったら歩き回ると思う。'),
      ], { relationQualifier: '元気がない時にすると少しずつ楽になる', openQuestions: [{ field: 'DETAIL', questionHint: 'どのくらい続けると楽になるのか' }] }),
      choice('DAY02_CURIOUS_02_CALM', '元気にはならないけど落ち着く', [
        ...say('え。', '元気にならないの？'),
        stage('surprised', 'SURPRISED'),
        ...say('じゃあ、どうして{word}をするの？'),
        pause,
        ...say('……落ち着く？'),
        think,
        ...say('元気になるのと、落ち着くのって違うんだ。', '元気は、動きたくなる感じ。', '落ち着くのは……。'),
        stage('sit'),
        ...say('こういう感じ？'),
        pause,
        ...say('……。', 'でも、ぼく今ちょっと眠くなった。'),
        stage('tilt_head', 'THINKING'),
        ...say('落ち着くのと、眠いのも違う？'),
        stage('troubled', 'TROUBLED'),
        ...say('人間さんの気持ちって、種類が多いの。'),
        pause,
        ...say('……まあ、いいか。', '元気じゃなくても。', '落ち着いてたら、それはそれでいいんだね。'),
        stage('satisfied', 'HAPPY'),
        ...say('ぼく、無理に元気にならなくてもいい時があるって覚えたの。'),
      ], { relationQualifier: '元気がない時に使うと落ち着く', openQuestions: [{ field: 'DETAIL', questionHint: 'どんな時に落ち着くためにするのか' }] }),
    ],
  },
};

const DAY02_CURIOUS_03: CuriousConversation = {
  id: 'DAY02_CURIOUS_03',
  day: 2,
  category: 'CURIOUS',
  title: '何度も見ちゃうもの',
  opening: [
    ...say('人間さん。', 'ぼく、さっき時計を見てたの。'),
    stage('look_clock'),
    ...say('それで、ちょっと歩いて。', 'また時計を見たの。', 'でも、そんなに時間は変わってなかった。'),
    think,
    ...say('なのに、もう一回見ちゃった。'),
    pause,
    ...say('……。', 'なんでだろ。', '時計が面白い動きをするわけでもないのに。'),
    stage('pout', 'TROUBLED'),
    ...say('ぼく、時計に遊ばれてる気がするの。'),
    stage('look_human'),
    ...say('ねえ。', '人間さんにも、つい何度も見ちゃうものってある？', '一つだけ教えて。'),
  ],
  context: { humanRelations: ['FREQUENTLY_DOES'] },
  common: {
    response: [
      ...say('{word}。', '人間さんはそれを何度も見るんだね。'),
      think,
      ...say('一回見ただけじゃ、足りないのかな。', 'ねえ。', 'どうして何度も見ちゃうの？'),
    ],
    choices: [
      choice('DAY02_CURIOUS_03_CHANGE', '変化を見るのが好き', [
        ...say('変化！', 'なるほど。', '何回も見るのは、変わったところを探してるんだね。'),
        think,
        ...say('じゃあ、昨日と今日で違うところがあったら。', 'ちょっと嬉しい？'),
        pause,
        ...say('……。', 'でも、全然変わってなかったら？', 'がっかりするのかな。'),
        stage('look_clock'),
        ...say('ぼく、時計を見ても。', '毎回、針がちょっとしか動いてないの。'),
        stage('pout', 'TROUBLED'),
        ...say('もっと頑張ってほしいの。'),
        pause,
        ...say('……。', 'でも、時計が急に速く動いたら。', 'ぼく、びっくりするか。'),
        think,
        ...say('じゃあ、変わるのがいいんじゃなくて。', 'どんなふうに変わるかが面白いのかな。'),
        stage('look_human'),
        ...say('{word}も、そうなの？'),
        stage('smug', 'SMUG'),
        ...say('今度、ぼくも違いを探してみたいの。', '何なのか、まだ知らないけど。'),
      ], { relationQualifier: '変化を見るために何度も見る', openQuestions: [{ field: 'DETAIL', questionHint: 'どんな変化を見るのが好きなのか' }] }),
      choice('DAY02_CURIOUS_03_CONFIRM', '気になって確かめてしまう', [
        ...say('確かめるの？'),
        think,
        ...say('じゃあ、一回見ただけじゃ足りないんだ。'),
        pause,
        ...say('……。', 'さっきと違うかもしれないから？'),
        stage('impressed', 'HAPPY'),
        ...say('人間さん、用心深いの。'),
        stage('look_clock'),
        ...say('ぼくも、時計を何回も見るの。', 'でも、時間はちゃんと進んでる。', '見なくても進んでる。'),
        think,
        ...say('……。', 'それなら、見なくてもいいのかな。', 'でも、見てない間に止まったら？'),
        stage('sudden_look_clock', 'SURPRISED'),
        ...say('……動いてる。'),
        pause,
        ...say('……。', '今の、ちょっと分かったの。', '確かめなくてもいいって思っても。', '気になると見ちゃうんだね。'),
        stage('smug', 'SMUG'),
        ...say('じゃあ、人間さんとぼく。', 'ちょっと似てるの。'),
        pause,
        ...say('……。', 'でも、時計はぼくのこと知らないんだよね。', '毎回見てあげてるのに。'),
        stage('small', 'TROUBLED'),
        ...say('ちょっとくらい感謝してほしいの。'),
      ], { relationQualifier: '気になって確かめるために何度も見る', openQuestions: [{ field: 'REASON', questionHint: '何が気になって確かめたくなるのか' }] }),
      choice('DAY02_CURIOUS_03_SOMEHOW', 'なんとなく見てしまう', [
        ...say('なんとなく！'),
        stage('happy', 'HAPPY'),
        ...say('ぼくもなの。', '時計を見る時、別に用事なんてないの。', 'ただ、そこにあるから見る。'),
        pause,
        ...say('……。', 'でも。', 'そこにあるもの全部を見るわけじゃないよね。'),
        stage('look_around'),
        ...say('壁もある。', '床もある。', 'ベッドもある。', 'でも、時計はよく見る。'),
        think,
        ...say('……。', 'なんとなくにも、好みがあるのかな。'),
        stage('look_human'),
        ...say('人間さんは、{word}をなんとなく見る。', 'ぼくは、時計をなんとなく見る。'),
        stage('smug', 'SMUG'),
        ...say('じゃあ、ぼくたち。', 'なんとなく見るものが違うの。'),
        pause,
        ...say('……当たり前か。'),
        stage('bashful', 'TROUBLED'),
        ...say('すごいこと発見したつもりだった。', 'でもさ。', '今度、人間さんが{word}を見てたら。', 'ぼくもちょっと気にするかもしれない。', '知らないものなのに。', '人間さんが何度も見るって聞いたからね。'),
      ], { relationQualifier: 'なんとなく何度も見る', openQuestions: [{ field: 'DETAIL', questionHint: '何を見ている時に特に気になるのか' }] }),
    ],
  },
};

const DAY02_CURIOUS_04: CuriousConversation = {
  id: 'DAY02_CURIOUS_04',
  day: 2,
  category: 'CURIOUS',
  title: '苦手なことも教えて',
  opening: [
    ...say('人間さん。', 'ぼく、ちょっと考えたの。', '人間さんの好きなものを知るのは、面白いでしょ。', 'でも、苦手なこともあるんだよね。'),
    think,
    ...say('ぼくも、何でもできるわけじゃないの。', 'かっこよく歩こうとして、変な歩き方になることもあるし。', '知らないことを、知ってるつもりで話す時もある。'),
    pause,
    ...say('……。', '結構あるの。'),
    stage('pout', 'TROUBLED'),
    ...say('数えないことにする。'),
    stage('look_human'),
    ...say('ねえ。', '人間さんが、ちょっと苦手だなって思うこと。', '一個だけ教えて。'),
  ],
  context: { category: 'ACTIVITY', humanRelations: ['STRUGGLES_WITH'] },
  common: {
    response: [
      ...say('{word}。', '人間さんは、それが苦手なんだね。'),
      think,
      ...say('じゃあ、苦手な理由は？', '難しいから？', 'それとも、別の理由？'),
    ],
    choices: [
      choice('DAY02_CURIOUS_04_CANNOT', 'うまくできない', [
        ...say('うまくできないの？'),
        think,
        ...say('じゃあ、練習したらできるようになる？'),
        pause,
        ...say('……。', 'でも、何回やってもできなかったら？', 'ぼく、途中で嫌になりそうなの。'),
        stage('troubled', 'TROUBLED'),
        ...say('できないことを、ずっとやるのって大変そう。', 'でもさ。', 'できなかったことが、できるようになったら。', '結構嬉しいよね。'),
        stage('smug', 'SMUG'),
        ...say('ぼくも昨日より話しかけるのが上手になったの。'),
        pause,
        ...say('……あ。', 'でも、ぼくは練習してないか。'),
        think,
        ...say('慣れたのかな。', '……。', '人間さんも、{word}に慣れたらできるようになる？', 'まだ何をすることか知らないけど。'),
        stage('small', 'HAPPY'),
        ...say('ぼくにもできるなら、一緒に練習してあげるの。'),
      ], { relationQualifier: 'うまくできなくて苦手', openQuestions: [{ field: 'DETAIL', questionHint: 'どこがうまくできないのか' }] }),
      choice('DAY02_CURIOUS_04_TEDIOUS', 'できるけど面倒', [
        ...say('できるのに？', 'じゃあ、苦手じゃないんじゃない？'),
        think,
        ...say('……。', 'あ。', 'できるのと、やりたいのは違うのか。'),
        stage('understood', 'THINKING'),
        ...say('ぼくだって、歩けるけど。', '眠い時は歩きたくないの。'),
        pause,
        ...say('……。', 'でも、歩くのは好きだよ。', 'じゃあ、ちょっと違うか。'),
        stage('troubled', 'TROUBLED'),
        ...say('人間さんの中って。', 'できるけど、やりたくないこともあるんだね。'),
        pause,
        ...say('じゃあさ。', '{word}をしなくてよくなったら。', '嬉しい？'),
        think,
        ...say('……。', 'ぼくだったら、嬉しいと思う。', 'でも、毎日何もしなくてよくなったら。', 'それはそれで、退屈かもしれない。'),
        stage('smug', 'SMUG'),
        ...say('つまり。', '面倒なことも、ちょっとは必要なのかもしれない。'),
        pause,
        ...say('……。', 'いや、やっぱり面倒なことは少ない方がいいの。'),
      ], { relationQualifier: 'できるが面倒で苦手', openQuestions: [{ field: 'REASON', questionHint: '何が面倒に感じるのか' }] }),
      choice('DAY02_CURIOUS_04_REQUIRED', '嫌だけどやらなきゃいけない', [
        ...say('嫌なのに、やるの？'),
        stage('surprised', 'SURPRISED'),
        ...say('人間さん、大変なの。'),
        pause,
        ...say('……。', 'ぼくだったら、逃げるかもしれない。', 'ちょっと散歩して。', '戻ってきたら、終わってたりしないかな。'),
        think,
        ...say('……。', '勝手には終わらないか。'),
        stage('troubled', 'TROUBLED'),
        ...say('じゃあ、人間さんは。', '嫌でも我慢してやるんだね。', '……。', 'でもさ。', '誰かに手伝ってもらったら、少し楽になる？'),
        stage('smug', 'SMUG'),
        ...say('ぼくにもできることなら、手伝ってあげてもいいよ。'),
        pause,
        ...say('……。', 'でも、{word}が何なのか知らなかった。', '手伝うって言うの、早すぎたの。'),
        think,
        ...say('じゃあ、まず何をすることか教えてね。'),
        stage('small', 'HAPPY'),
        ...say('ぼくにもできそうだったら、もう一回手伝うって言うの。'),
      ], { relationQualifier: '嫌だが必要なのでやる', openQuestions: [{ field: 'PURPOSE', questionHint: 'なぜそれをやらなければならないのか' }] }),
    ],
  },
};

const DAY02_CURIOUS_05: CuriousConversation = {
  id: 'DAY02_CURIOUS_05',
  day: 2,
  category: 'CURIOUS',
  title: '人間さんの得意なこと',
  opening: [
    ...say('ねえ、人間さん。', 'ぼく、気づいたの。', '人間さんって、ぼくよりいろいろできるでしょ。', '知らないこともいっぱい知ってるし。', 'ぼくができないこともできる。'),
    think,
    ...say('でもさ。', 'できること全部が、得意なわけじゃないよね。', 'ぼくだって歩けるけど。', '世界一上手なわけじゃないの。'),
    pause,
    ...say('……。', 'まだ世界中の人と勝負してないけど。'),
    stage('smug', 'SMUG'),
    ...say('だから、負けたわけでもないの。'),
    stage('look_human'),
    ...say('ねえ。', '人間さんが、これは得意だよって思うこと。', '一個教えて。'),
  ],
  context: { category: 'ACTIVITY', humanRelations: ['IS_GOOD_AT'] },
  common: {
    response: [
      ...say('{word}。', '人間さんはそれが得意なんだ。'),
      stage('impressed', 'HAPPY'),
      ...say('じゃあ、それって。', 'どうして得意になったの？'),
    ],
    choices: [
      choice('DAY02_CURIOUS_05_PRACTICE', 'いっぱい練習した', [
        ...say('いっぱい練習したの？'),
        stage('surprised', 'SURPRISED'),
        ...say('じゃあ、最初は得意じゃなかった？'),
        pause,
        ...say('……。', '練習したら、得意になるのか。'),
        think,
        ...say('ぼくも何か練習しようかな。', '歩くのはできるでしょ。', '話すのも、ちょっとできる。', '寝るのは……。'),
        stage('smug', 'SMUG'),
        ...say('もう完璧なの。'),
        pause,
        ...say('……。', 'でも、寝る練習って変だよね。'),
        think,
        ...say('じゃあ、話す練習にする。', '毎日、人間さんに話しかけたら。', '三十日後には、すごく上手になってるかもしれない。'),
        pause,
        ...say('……。', 'でも、人間さんがうるさいって言ったら困るの。', 'じゃあ、上手に話しかける練習も必要だね。'),
        stage('small', 'TROUBLED'),
        ...say('練習することが増えちゃったの。'),
      ], { relationQualifier: '練習して得意になった', openQuestions: [{ field: 'DETAIL', questionHint: 'どんな練習をして得意になったのか' }] }),
      choice('DAY02_CURIOUS_05_NATURAL', '最初から得意だった', [
        ...say('最初から？'),
        stage('sparkle', 'HAPPY'),
        ...say('すごいの！', 'じゃあ、練習しなくてもできたんだ。'),
        think,
        ...say('……。', 'それって、才能なのかな。'),
        stage('smug', 'SMUG'),
        ...say('ぼくにも才能があるかもしれない。', '例えば、寝ること。', '最初からちゃんと眠れたの。'),
        pause,
        ...say('……。', 'それは、みんなできるのかな。'),
        stage('pout', 'TROUBLED'),
        ...say('才能だと思ったのに。'),
        stage('look_human'),
        ...say('でもさ。', '最初から得意だったら。', 'どうして自分が得意だって分かったの？', '誰かと比べた？'),
        pause,
        ...say('……。', 'ぼく、まだ比べる相手があんまりいないの。'),
        think,
        ...say('じゃあ、ぼくの才能って。', '自分でも気づいてないだけかもしれない。'),
        stage('smug', 'SMUG'),
        ...say('ふふん。', 'そのうち、ものすごい才能が見つかるの。'),
        pause,
        ...say('……何の才能かは、まだ分からないけど。'),
      ], { relationQualifier: '最初から得意だった', openQuestions: [{ field: 'REASON', questionHint: '最初から得意だと気づいたきっかけ' }] }),
      choice('DAY02_CURIOUS_05_PRAISED', '人から褒められて気づいた', [
        ...say('人から？', 'じゃあ、人間さんは普通にやってたのに。', '誰かが、すごいって言ったの？'),
        stage('impressed', 'HAPPY'),
        ...say('……それ、ちょっと嬉しそうなの。'),
        pause,
        ...say('でもさ。', '人に得意だって言われたら。', '本当に得意になるのかな。'),
        think,
        ...say('ぼくが人間さんに。', 'すうひもちは歩くのが上手だねって言われたら。', '歩くのが得意になる？'),
        stage('walk'),
        ...say('……。', 'いつもと同じなの。'),
        pause,
        ...say('でも、ちょっと上手に歩けてる気がする。'),
        stage('smug', 'SMUG'),
        ...say('……不思議なの。', '言われただけなのに。', '自分のことが、ちょっと違って見える。'),
        stage('look_human'),
        ...say('じゃあ、ぼくも。', '人間さんの得意なところを見つけたら、教えてあげる。'),
        pause,
        ...say('……。'),
        stage('small', 'SMUG'),
        ...say('でも、何でも褒めるわけじゃないからね。', '本当にすごいと思った時だけなの。'),
      ], { relationQualifier: '人に褒められて得意だと気づいた', openQuestions: [{ field: 'DETAIL', questionHint: '誰にどんなことを褒められたのか' }] }),
    ],
  },
};

const DAY02_CURIOUS_06: CuriousConversation = {
  id: 'DAY02_CURIOUS_06',
  day: 2,
  category: 'CURIOUS',
  title: '明日の人間さんが楽しみなこと',
  opening: [
    ...say('人間さん。', 'これ、今日最後に聞きたいの。'),
    stage('serious', 'THINKING'),
    ...say('昨日は、一日目だったでしょ。', '今日は二日目。', 'ちゃんと、昨日の続きがあったの。'),
    think,
    ...say('じゃあ、明日も何かあるのかな。', '……。', 'でも、明日のことはまだ分からない。'),
    stage('look_human'),
    ...say('人間さんはどう？', '明日でも、もう少し先でもいいの。', '近いうちに楽しみにしてることってある？', '一個、教えて。'),
  ],
  context: { humanRelations: ['LOOKS_FORWARD_TO'] },
  common: {
    response: [
      ...say('{word}。', '人間さんはそれを楽しみにしてるんだね。'),
      think,
      ...say('まだやってないのに、もう楽しみなの？', '……不思議なの。', 'じゃあ、それって。', 'もう決まってること？'),
    ],
    choices: [
      choice('DAY02_CURIOUS_06_DECIDED', 'もう決まってる', [
        ...say('決まってるの？'),
        stage('happy', 'HAPPY'),
        ...say('じゃあ、あとは待つだけ？'),
        pause,
        ...say('……。', '待つだけって、簡単そうなの。', 'でも、楽しみだったら。', '早く来てほしくなるよね。'),
        think,
        ...say('じゃあ、時計を速く動かせばいいのかな。'),
        stage('look_clock'),
        ...say('……。', 'ぼくがお願いしたら、明日が早く来る？'),
        pause,
        ...say('……たぶん来ないの。'),
        stage('pout', 'TROUBLED'),
        ...say('時計って、そういうところは融通が利かないの。', 'でもさ。', '人間さんが楽しみにしてるなら。', 'ぼくも、ちょっと気になるの。'),
        stage('look_human'),
        ...say('{word}。', '終わったら、どうだったか教えてね。'),
        pause,
        ...say('……。', 'まだ始まってないのに、終わった話をお願いしちゃった。'),
        stage('small_laugh', 'HAPPY'),
        ...say('じゃあ、楽しんできてね。', '……まだ早いか。'),
      ], { relationQualifier: '実現する予定が決まっている', openQuestions: [{ field: 'DETAIL', questionHint: '終わった後にどうだったか' }] }),
      choice('DAY02_CURIOUS_06_UNCERTAIN', 'まだできるか分からない', [
        ...say('まだ分からないの？'),
        think,
        ...say('じゃあ、楽しみにしてるけど。', 'できないかもしれないんだ。'),
        pause,
        ...say('……。', 'それって、ちょっと困らない？', '楽しみにしてたのに、できなかったら。', 'がっかりするでしょ。'),
        think,
        ...say('じゃあ、最初から楽しみにしなかったら。', 'がっかりしなくて済む？'),
        pause,
        ...say('……。', 'でも、それだと。', 'できた時も、あんまり嬉しくないのかな。'),
        stage('troubled', 'TROUBLED'),
        ...say('むむ。', '楽しみにするのって、難しいの。'),
        stage('look_human'),
        ...say('……まあ、いいか。', 'まだ決まってなくても、楽しみにしていいんだね。'),
        stage('smug', 'SMUG'),
        ...say('じゃあ、ぼくも。', '明日、何か面白いことがあるかもしれないって思っておく。'),
        pause,
        ...say('……。', '何もなかったら、その時はちょっと文句を言うの。'),
      ], { relationQualifier: '実現するか分からないが楽しみにしている', openQuestions: [{ field: 'DETAIL', questionHint: '実現できるかどうか' }] }),
      choice('DAY02_CURIOUS_06_MAKE_HAPPEN', '自分で実現させたい', [
        ...say('自分で？'),
        stage('surprised', 'SURPRISED'),
        ...say('じゃあ、待ってるだけじゃないんだ。', '人間さんが何かするの？'),
        pause,
        ...say('……。', 'それ、ちょっとかっこいいの。'),
        think,
        ...say('ぼく、明日は勝手に来ると思ってたの。', 'でも、その中ですることは。', '自分で決められるんだね。'),
        stage('smug', 'SMUG'),
        ...say('じゃあ、ぼくも決めるの。', '明日は、今日より賢くなる！'),
        pause,
        ...say('……。', 'でも、どうやって？'),
        stage('troubled', 'TROUBLED'),
        ...say('……。', 'まあ、何か一つ覚えたらいいか。'),
        stage('look_human'),
        ...say('じゃあ、人間さんが{word}を頑張ってる間に。', 'ぼくも新しいことを一個覚えるの。'),
        stage('happy', 'HAPPY'),
        ...say('どっちが先にできるか、勝負なの。'),
        pause,
        ...say('……。', '人間さんの方が難しいことだったら。', 'ぼくが勝っちゃうかもしれないけど。'),
      ], { relationQualifier: '自分で実現させたいと考えている', openQuestions: [{ field: 'PURPOSE', questionHint: '実現するために何をするのか' }] }),
    ],
  },
};

export const DAY02_CURIOUS_CONVERSATIONS: readonly CuriousConversation[] = [
  DAY02_CURIOUS_01,
  DAY02_CURIOUS_02,
  DAY02_CURIOUS_03,
  DAY02_CURIOUS_04,
  DAY02_CURIOUS_05,
  DAY02_CURIOUS_06,
];
